import { chromium } from 'playwright';

const base = process.env.BASE_URL || 'http://127.0.0.1:8080';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(`${base}/admin/login`);
await page.fill('input[name="username"]', process.env.ADMIN_USER || 'admin');
await page.fill('input[name="password"]', process.env.ADMIN_PASSWORD || 'admin123');
await Promise.all([page.waitForURL('**/admin**'), page.click('button')]);
await page.click('[data-view="licenses"]');
await page.waitForSelector('#productFilter');
await page.selectOption('#productFilter', { index: 0 });
await page.click('#licenses .layui-card-header button');
await page.waitForSelector('#genProduct');
if ((await page.locator('#genProduct').count()) !== 1) throw new Error('generation dialog product control is missing');
await page.keyboard.press('Escape');
await page.reload();
if (!page.url().includes('#licenses')) throw new Error('license view hash was not preserved after refresh');
await page.click('[data-view="logs"]');
await page.waitForSelector('#auditSource');
await page.selectOption('#auditSource', 'client');
await page.reload();
await page.waitForSelector('#auditSource');
if ((await page.inputValue('#auditSource')) !== 'client') throw new Error('audit filter was not persisted');
await page.click('[data-view="devices"]');
await page.waitForSelector('#deviceFilters');
if ((await page.locator('#deviceOnline option').count()) < 3) throw new Error('device filters missing');
await page.click('[data-view="overview"]');
await page.waitForSelector('#reportCard');
console.log('PLAYWRIGHT SMOKE PASS');
await browser.close();
