#using <System.dll>
#using <System.Drawing.dll>
#using <System.Windows.Forms.dll>
using namespace System;
using namespace System::Drawing;
using namespace System::Windows::Forms;

public ref class HeartbeatForm : public Form {
public:
    HeartbeatForm() {
        Text = L"Heartbeat details"; Width = 480; Height = 300;
        auto info = gcnew Label(); info->Dock = DockStyle::Fill; info->Padding = System::Windows::Forms::Padding(24);
        info->Text = L"Status: waiting\nProduct: 1\nHeartbeat interval: 5 seconds\nDevice: generated by SDK";
        Controls->Add(info);
    }
};

public ref class MainForm : public Form {
private: TextBox^ key; Label^ announcement; Label^ versions;
public:
    MainForm() {
        Text = L"License SDK v3"; Width = 560; Height = 430;
        StartPosition = FormStartPosition::CenterScreen; BackColor = Color::FromArgb(247,249,252);
        auto title = gcnew Label(); title->Text = L"Product license"; title->Font = gcnew System::Drawing::Font(L"Segoe UI", 20, FontStyle::Bold); title->Location = Point(36, 28); title->AutoSize = true; Controls->Add(title);
        versions = gcnew Label(); versions->Text = L"Latest version: loading    Local version: 3.0.0"; versions->Location = Point(40, 72); versions->AutoSize = true; Controls->Add(versions);
        announcement = gcnew Label(); announcement->Text = L"Announcement will appear after product bootstrap."; announcement->Location = Point(40, 110); announcement->Size = Drawing::Size(465, 70); announcement->BorderStyle = BorderStyle::FixedSingle; announcement->Padding = System::Windows::Forms::Padding(12); Controls->Add(announcement);
        auto label = gcnew Label(); label->Text = L"License key"; label->Location = Point(40, 205); label->AutoSize = true; Controls->Add(label);
        key = gcnew TextBox(); key->Location = Point(40, 230); key->Width = 465; Controls->Add(key);
        auto login = gcnew Button(); login->Text = L"Login"; login->Location = Point(40, 280); login->Width = 465; login->Height = 42; login->BackColor = Color::FromArgb(35,99,235); login->ForeColor = Color::White; login->Click += gcnew EventHandler(this, &MainForm::Login); Controls->Add(login);
        auto footer = gcnew Label(); footer->Text = L"v3 encrypted transport | heartbeat 5 seconds"; footer->Location = Point(40, 350); footer->AutoSize = true; footer->ForeColor = Color::Gray; Controls->Add(footer);
    }
private:
    void Login(Object^, EventArgs^) {
        if (String::IsNullOrWhiteSpace(key->Text)) { MessageBox::Show(L"Enter a license key", L"Notice"); return; }
        MessageBox::Show(L"Login succeeded\nExpires: server response", L"Login succeeded", MessageBoxButtons::OK, MessageBoxIcon::Information);
        (gcnew HeartbeatForm())->Show(this);
    }
};

[STAThread] int main(array<String^>^) { Application::EnableVisualStyles(); Application::SetCompatibleTextRenderingDefault(false); Application::Run(gcnew MainForm()); return 0; }
