#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <winhttp.h>
#include <wincrypt.h>
#include <bcrypt.h>
#include <atomic>
#include <chrono>
#include <iomanip>
#include <random>
#include <sstream>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>
#pragma comment(lib, "winhttp.lib")
#pragma comment(lib, "advapi32.lib")
#pragma comment(lib, "crypt32.lib")
#pragma comment(lib, "bcrypt.lib")
inline BOOL crypt_decode_object(DWORD a, LPCSTR b, const BYTE* c, DWORD d, DWORD e, void* f, DWORD, DWORD* h) { return CryptDecodeObjectEx(a,b,c,d,e,nullptr,f,h); }
inline BOOL crypt_decode_object(DWORD a, LPCSTR b, const BYTE* c, DWORD d, DWORD e, void* g, DWORD* h) { return CryptDecodeObjectEx(a,b,c,d,e,nullptr,g,h); }
#define CryptDecodeObject(...) crypt_decode_object(__VA_ARGS__)

constexpr int ID_KEY = 1001, ID_LOGIN = 1002, ID_STATUS = 1003;
constexpr UINT WM_HEARTBEAT_STATUS = WM_APP + 1;
std::atomic_bool heartbeat_running{false};
std::atomic_bool logout_sent{false};
std::string active_license;
const std::string PRODUCT_CODE = "1";
const std::string PRODUCT_NAME = "debug";
const std::string CLIENT_VERSION = "3.0.0";
std::atomic_bool product_ready{false};

// SubjectPublicKeyInfo DER, base64 encoded. Rotate this per release build.
constexpr const char* SERVER_PUBLIC_KEY_B64 =
"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuwo3JtKNfLGY+VmeyQbn"
"MCAwrzZL1V0eMMXB7nxsc5rOS2QyQTLW5FEtGeaLR9Eeo8xICdFukVKsL/5+PjnE"
"aFuFma1EQdUxeR+RwWr0vVSU5gxugWA7QpxLj+H2i1CSalIWT1OBdcUP/enMO3a5"
"GuUxThcBgLnBSuMZev/STKiusAr0GX4WUE3Uce/3q4Zr2T87CPjPSSYbm8YHCoUX"
"huy7F1/D4mGe+49m1d43Yxfwv2RstzxYGt2K6rWgqiuxuH5lp6dIMBQCGb/3+VI+"
"RrdDTdYPTL2s3PpYokqqDmosuANooAxhFbvk01Ysk8se+Dw1F9C7hvqQI69szUON"
"tQIDAQAB";

std::wstring utf8_to_wide(const std::string& s) { if(s.empty()) return L""; int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0); std::wstring r(n,L'\0'); MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),r.data(),n); return r; }
std::string wide_to_utf8(const std::wstring& s) { if(s.empty()) return ""; int n=WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0,nullptr,nullptr); std::string r(n,'\0'); WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),r.data(),n,nullptr,nullptr); return r; }
std::string json_escape(const std::string& s) { std::string r; for(char c:s){if(c=='\\'||c=='"')r+='\\';r+=c;}return r; }
std::string b64url(const std::vector<BYTE>& data) { DWORD n=0; CryptBinaryToStringA(data.data(),(DWORD)data.size(),CRYPT_STRING_BASE64|CRYPT_STRING_NOCRLF,nullptr,&n); std::vector<char> buffer(n); CryptBinaryToStringA(data.data(),(DWORD)data.size(),CRYPT_STRING_BASE64|CRYPT_STRING_NOCRLF,buffer.data(),&n); std::string r(buffer.data()); for(char& c:r){if(c=='+')c='-';else if(c=='/')c='_';}while(!r.empty()&&r.back()=='=')r.pop_back();return r; }
std::vector<BYTE> b64url_decode(std::string s) { for(char& c:s){if(c=='-')c='+';else if(c=='_')c='/';}while(s.size()%4)s+='=';DWORD n=0; if(!CryptStringToBinaryA(s.data(),(DWORD)s.size(),CRYPT_STRING_BASE64,nullptr,&n,nullptr,nullptr))throw std::runtime_error("invalid base64");std::vector<BYTE> r(n);CryptStringToBinaryA(s.data(),(DWORD)s.size(),CRYPT_STRING_BASE64,r.data(),&n,nullptr,nullptr);return r; }
std::vector<BYTE> random_bytes(size_t n) { std::vector<BYTE> r(n); if(BCryptGenRandom(nullptr,r.data(),(ULONG)n,BCRYPT_USE_SYSTEM_PREFERRED_RNG)<0)throw std::runtime_error("random failed");return r; }
std::string hex_sha256(const std::string& s) { HCRYPTPROV p=0;HCRYPTHASH h=0;BYTE out[32];DWORD n=32;if(!CryptAcquireContextW(&p,nullptr,nullptr,PROV_RSA_AES,CRYPT_VERIFYCONTEXT)||!CryptCreateHash(p,CALG_SHA_256,0,0,&h)||!CryptHashData(h,(const BYTE*)s.data(),(DWORD)s.size(),0)||!CryptGetHashParam(h,HP_HASHVAL,out,&n,0))throw std::runtime_error("hash failed");std::ostringstream o;o<<std::hex<<std::setfill('0');for(DWORD i=0;i<n;i++)o<<std::setw(2)<<(unsigned)out[i];CryptDestroyHash(h);CryptReleaseContext(p,0);return o.str(); }
std::string device_code() { HKEY key;wchar_t guid[256]{};DWORD size=sizeof(guid),type=0;if(RegOpenKeyExW(HKEY_LOCAL_MACHINE,L"SOFTWARE\\Microsoft\\Cryptography",0,KEY_READ|KEY_WOW64_64KEY,&key)!=ERROR_SUCCESS||RegQueryValueExW(key,L"MachineGuid",nullptr,&type,(BYTE*)guid,&size)!=ERROR_SUCCESS)throw std::runtime_error("device id failed");RegCloseKey(key);DWORD serial=0;GetVolumeInformationW(L"C:\\",nullptr,0,&serial,nullptr,nullptr,nullptr,0);return "dev-v1-"+hex_sha256(wide_to_utf8(guid)+":"+std::to_string(serial)); }

struct Response { DWORD status{}; std::string body; };
std::string json_value(const std::string& j,const std::string& key){std::string m="\""+key+"\":\"";auto p=j.find(m);if(p==std::string::npos)return"";p+=m.size();auto e=j.find('"',p);return e==std::string::npos?"":j.substr(p,e-p);}
std::vector<BYTE> aes_gcm(bool encrypt,const std::vector<BYTE>& key,const std::vector<BYTE>& iv,const std::string& aad,const std::vector<BYTE>& input,std::vector<BYTE>& tag){BCRYPT_ALG_HANDLE alg=nullptr;BCRYPT_KEY_HANDLE kh=nullptr;DWORD obj=0,cb=0,outSize=(DWORD)input.size();if(BCryptOpenAlgorithmProvider(&alg,BCRYPT_AES_ALGORITHM,nullptr,0)<0)throw std::runtime_error("aes provider failed");BCryptSetProperty(alg,BCRYPT_CHAINING_MODE,(PUCHAR)BCRYPT_CHAIN_MODE_GCM,(ULONG)sizeof(BCRYPT_CHAIN_MODE_GCM),0);BCryptGetProperty(alg,BCRYPT_OBJECT_LENGTH,(PUCHAR)&obj,sizeof(obj),&cb,0);std::vector<BYTE> object(obj);if(BCryptGenerateSymmetricKey(alg,&kh,object.data(),obj,(PUCHAR)key.data(),(ULONG)key.size(),0)<0)throw std::runtime_error("aes key failed");BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO info;BCRYPT_INIT_AUTH_MODE_INFO(info);info.pbNonce=(PUCHAR)iv.data();info.cbNonce=(ULONG)iv.size();info.pbAuthData=(PUCHAR)aad.data();info.cbAuthData=(ULONG)aad.size();if(encrypt){tag.resize(16);info.pbTag=tag.data();info.cbTag=(ULONG)tag.size();}else{info.pbTag=tag.data();info.cbTag=(ULONG)tag.size();}std::vector<BYTE> out(input.size());NTSTATUS st=encrypt?BCryptEncrypt(kh,(PUCHAR)input.data(),(ULONG)input.size(),&info,nullptr,0,out.data(),(ULONG)out.size(),&outSize,0):BCryptDecrypt(kh,(PUCHAR)input.data(),(ULONG)input.size(),&info,nullptr,0,out.data(),(ULONG)out.size(),&outSize,0);BCryptDestroyKey(kh);BCryptCloseAlgorithmProvider(alg,0);if(st<0)throw std::runtime_error(encrypt?"encrypt failed":"response authentication failed");out.resize(outSize);return out;}
std::vector<BYTE> rsa_oaep(const std::vector<BYTE>& secret){std::vector<BYTE> der=b64url_decode(SERVER_PUBLIC_KEY_B64);CERT_PUBLIC_KEY_INFO* info=nullptr;DWORD cb=0;if(!CryptDecodeObject(X509_ASN_ENCODING,X509_PUBLIC_KEY_INFO,der.data(),(DWORD)der.size(),0,nullptr,0,&cb))throw std::runtime_error("public key decode failed");std::vector<BYTE> mem(cb);info=(CERT_PUBLIC_KEY_INFO*)mem.data();if(!CryptDecodeObject(X509_ASN_ENCODING,X509_PUBLIC_KEY_INFO,der.data(),(DWORD)der.size(),0,info,&cb))throw std::runtime_error("public key parse failed");BCRYPT_KEY_HANDLE key=nullptr;if(!CryptImportPublicKeyInfoEx2(X509_ASN_ENCODING,info,0,nullptr,&key))throw std::runtime_error("public key import failed");BCRYPT_OAEP_PADDING_INFO padding{BCRYPT_SHA1_ALGORITHM,nullptr,0};ULONG n=0;BCryptEncrypt(key,(PUCHAR)secret.data(),(ULONG)secret.size(),&padding,nullptr,0,nullptr,0,&n,BCRYPT_PAD_OAEP);std::vector<BYTE> out(n);if(BCryptEncrypt(key,(PUCHAR)secret.data(),(ULONG)secret.size(),&padding,nullptr,0,out.data(),n,&n,BCRYPT_PAD_OAEP)<0)throw std::runtime_error("key wrapping failed");BCryptDestroyKey(key);out.resize(n);return out;}
Response http_post(const std::string& endpoint,const std::string& body){HINTERNET s=WinHttpOpen(L"LicenseMvpGui/3.0",WINHTTP_ACCESS_TYPE_NO_PROXY,nullptr,nullptr,0),c=s?WinHttpConnect(s,L"127.0.0.1",8080,0):nullptr;std::wstring p(endpoint.begin(),endpoint.end());HINTERNET r=c?WinHttpOpenRequest(c,L"POST",p.c_str(),nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,0):nullptr;if(!r)throw std::runtime_error("cannot connect license service");const wchar_t* h=L"Content-Type: application/octet-stream\r\n";if(!WinHttpSendRequest(r,h,(DWORD)-1,(void*)body.data(),(DWORD)body.size(),(DWORD)body.size(),0)||!WinHttpReceiveResponse(r,nullptr))throw std::runtime_error("network failed");DWORD status=0,n=sizeof(status);WinHttpQueryHeaders(r,WINHTTP_QUERY_STATUS_CODE|WINHTTP_QUERY_FLAG_NUMBER,nullptr,&status,&n,nullptr);std::string out;char b[4096];DWORD got=0;while(WinHttpReadData(r,b,sizeof(b),&got)&&got)out.append(b,got);WinHttpCloseHandle(r);WinHttpCloseHandle(c);WinHttpCloseHandle(s);return{status,out};}
Response secure_post(const std::string& action,const std::string& license){std::string path="/api/v3/licenses/"+action,device=device_code();auto key=random_bytes(32),iv=random_bytes(12),nonce=random_bytes(24);std::string nonceText=b64url(nonce),ts=std::to_string(std::time(nullptr)),plain="{\"license_key\":\""+json_escape(license)+"\",\"product_code\":\""+PRODUCT_CODE+"\",\"device_id\":\""+device+"\",\"device_name\":\""+device+"\",\"_path\":\""+path+"\",\"_timestamp\":\""+ts+"\",\"_nonce\":\""+nonceText+"\"}";std::vector<BYTE>tag,bytes(plain.begin(),plain.end()),cipher=aes_gcm(true,key,iv,"",bytes,tag),wrapped=rsa_oaep(key);std::string packet("LK3\0",4);packet.append((char*)wrapped.data(),wrapped.size());packet.append((char*)iv.data(),iv.size());packet.append((char*)tag.data(),tag.size());packet.append((char*)cipher.data(),cipher.size());Response r=http_post(path,packet);if(r.body.size()<32||r.body.compare(0,4,"LR3\0",4)!=0)return r;std::vector<BYTE>riv(r.body.begin()+4,r.body.begin()+16),rtag(r.body.begin()+16,r.body.begin()+32),rc(r.body.begin()+32,r.body.end()),decoded=aes_gcm(false,key,riv,"",rc,rtag);r.body.assign(decoded.begin(),decoded.end());return r;}
Response secure_bootstrap(){std::string path="/api/v3/products/bootstrap",device=device_code();auto key=random_bytes(32),iv=random_bytes(12),nonce=random_bytes(24);std::string nonceText=b64url(nonce),ts=std::to_string(std::time(nullptr)),plain="{\"product_code\":\""+PRODUCT_CODE+"\",\"client_version\":\""+CLIENT_VERSION+"\",\"device_id\":\""+device+"\",\"device_name\":\""+device+"\",\"_path\":\""+path+"\",\"_timestamp\":\""+ts+"\",\"_nonce\":\""+nonceText+"\"}";std::vector<BYTE>tag,bytes(plain.begin(),plain.end()),cipher=aes_gcm(true,key,iv,"",bytes,tag),wrapped=rsa_oaep(key);std::string packet("LK3\0",4);packet.append((char*)wrapped.data(),wrapped.size());packet.append((char*)iv.data(),iv.size());packet.append((char*)tag.data(),tag.size());packet.append((char*)cipher.data(),cipher.size());Response r=http_post(path,packet);if(r.body.size()<32||r.body.compare(0,4,"LR3\0",4)!=0)return r;std::vector<BYTE>riv(r.body.begin()+4,r.body.begin()+16),rtag(r.body.begin()+16,r.body.begin()+32),rc(r.body.begin()+32,r.body.end()),decoded=aes_gcm(false,key,riv,"",rc,rtag);r.body.assign(decoded.begin(),decoded.end());return r;}
std::wstring error_text(const std::string& b,bool offline){std::wstring p=offline?L"已下线：":L"登录失败：";if(b.find("license_suspended")!=std::string::npos)return p+L"卡密已被封禁。";if(b.find("license_expired")!=std::string::npos)return p+L"卡密已到期。";if(b.find("license_revoked")!=std::string::npos)return p+L"卡密已被撤销。";if(b.find("device_not_bound")!=std::string::npos)return p+L"设备唯一码未绑定或已失效。";if(b.find("device_limit_reached")!=std::string::npos)return p+L"设备数量已达上限。";if(b.find("invalid_license")!=std::string::npos)return p+L"卡密错误。";auto code=json_value(b,"error");return p+(code.empty()?L"验证失败。":L"加密协议错误："+utf8_to_wide(code));}
void set_status(HWND w,const std::wstring& s){SetWindowTextW(GetDlgItem(w,ID_STATUS),s.c_str());} void post_status(HWND w,const std::wstring& s){PostMessageW(w,WM_HEARTBEAT_STATUS,0,(LPARAM)new std::wstring(s));}
bool ensure_product(HWND w){try{set_status(w,L"Checking product...");Response r=secure_bootstrap();if(r.status!=200){if(r.body.find("product_not_found")!=std::string::npos)set_status(w,L"Product does not exist.");else if(r.body.find("product_disabled")!=std::string::npos)set_status(w,L"Product is disabled.");else if(r.body.find("client_version_too_old")!=std::string::npos){auto u=json_value(r.body,"update_url");set_status(w,L"Client version is too old. Please update.");if(!u.empty())post_status(w,utf8_to_wide("Update: "+u));}else set_status(w,L"Product verification failed.");return false;}product_ready=true;auto title=json_value(r.body,"title"),announcement=json_value(r.body,"content"),version=json_value(r.body,"version");if(!announcement.empty()){std::wstring msg=L"公告";if(!title.empty())msg+=L" ["+utf8_to_wide(title)+L"]";msg+=L"\r\n"+utf8_to_wide(announcement);post_status(w,msg);}if(!version.empty()&&version!=CLIENT_VERSION)post_status(w,L"New version available: "+utf8_to_wide(version));return true;}catch(...){set_status(w,L"Product verification network error.");return false;}}
void heartbeat(HWND w,const std::string& license){heartbeat_running=false;heartbeat_running=true;std::thread([w,license]{while(heartbeat_running){std::this_thread::sleep_for(std::chrono::seconds(5));if(!heartbeat_running)break;try{Response r=secure_post("heartbeat",license);if(r.status==200)post_status(w,L"登录成功\r\n心跳验证正常（v3 加密）");else if(r.status==401||r.status==403){heartbeat_running=false;post_status(w,error_text(r.body,true));}}catch(...){post_status(w,L"心跳网络异常，5 秒后重试。");}}}).detach();}
void login(HWND w){wchar_t buf[256]{};GetWindowTextW(GetDlgItem(w,ID_KEY),buf,256);std::wstring key=buf;if(key.empty()){set_status(w,L"请输入卡密。");return;}EnableWindow(GetDlgItem(w,ID_LOGIN),FALSE);set_status(w,L"正在验证 v3 加密连接...");try{Response r=secure_post("activate",wide_to_utf8(key));if(r.status==200){active_license=wide_to_utf8(key);logout_sent=false;std::string e=json_value(r.body,"expires_at");std::wstring out=L"登录成功\r\n到期时间："+(e.empty()?L"永久":utf8_to_wide(e.substr(0,19)));if(!e.empty()&&out.size()>10)out[10]=L' ';set_status(w,out);heartbeat(w,active_license);}else set_status(w,error_text(r.body,false));}catch(const std::exception& e){set_status(w,utf8_to_wide(e.what()));}EnableWindow(GetDlgItem(w,ID_LOGIN),TRUE);}
void send_logout(){if(logout_sent.exchange(true)||active_license.empty())return;heartbeat_running=false;try{secure_post("logout",active_license);}catch(...){}}
LRESULT CALLBACK proc(HWND w,UINT m,WPARAM a,LPARAM l){if(m==WM_HEARTBEAT_STATUS){auto* s=(std::wstring*)l;set_status(w,*s);delete s;return 0;}if(m==WM_COMMAND&&LOWORD(a)==ID_LOGIN){if(ensure_product(w))login(w);return 0;}if(m==WM_CLOSE){send_logout();DestroyWindow(w);return 0;}if(m==WM_DESTROY){send_logout();PostQuitMessage(0);return 0;}return DefWindowProcW(w,m,a,l);}
int WINAPI wWinMain(HINSTANCE h,HINSTANCE,PWSTR,int show){WNDCLASSW c{};c.hInstance=h;c.lpszClassName=L"LicenseV2Gui";c.lpfnWndProc=proc;c.hCursor=LoadCursor(nullptr,IDC_ARROW);c.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&c);HWND w=CreateWindowExW(0,c.lpszClassName,L"卡密验证测试（v2 加密）",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,500,310,nullptr,nullptr,h,nullptr);CreateWindowW(L"STATIC",L"卡密",WS_CHILD|WS_VISIBLE,34,32,100,22,w,nullptr,h,nullptr);CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"",WS_CHILD|WS_VISIBLE|ES_AUTOHSCROLL,34,58,420,30,w,(HMENU)ID_KEY,h,nullptr);CreateWindowW(L"BUTTON",L"登录验证",WS_CHILD|WS_VISIBLE|BS_DEFPUSHBUTTON,34,105,120,34,w,(HMENU)ID_LOGIN,h,nullptr);CreateWindowW(L"STATIC",L"使用 RSA-OAEP + AES-256-GCM 加密请求与响应",WS_CHILD|WS_VISIBLE,34,153,420,22,w,nullptr,h,nullptr);CreateWindowW(L"STATIC",L"等待验证。",WS_CHILD|WS_VISIBLE|SS_LEFT,34,184,420,64,w,(HMENU)ID_STATUS,h,nullptr);ShowWindow(w,show);UpdateWindow(w);MSG msg;while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
